spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/tanda_db}
    username: ${SPRING_DATASOURCE_USERNAME:tanda_user}
    password: ${SPRING_DATASOURCE_PASSWORD:tanda_password}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
    baseline-on-migrate: true

app:
  cookie:
    secure: true
  cors:
    allowed-origins:
      - https://tanda.kz
      - https://www.tanda.kz
      - https://usmansulaimanov.github.io
      - https://tanda-xi.vercel.app

google:
  client-id: ${GOOGLE_CLIENT_ID:470329734598-c32dk937vu2hgkbvblqjuvi43noc1mu9.apps.googleusercontent.com}
